Palap\ImageTagBundle\Entity\ImageTag:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    filename:
      type: string
      length: 255
    width:
      type: integer
    height:
      type: integer
    tags:
      type: text
      nullable: true
  lifecycleCallbacks: {  }
